### ISSUE TITLE
Funding yDaemon Team

### ISSUE THREAD

**Issue by Majorfi** [yearn/ychad-audit#106]
### Scope

yDaemon is an API, written in go, to provide an easy access to processed data from Yearn's ecosystem. It's now used in various projects and is becoming a milestone for our products:
- [yBribe](https://yBribe.com)
- [yCRV](https://y.finance)
- [Vaults at Yearn](https://vaults.yearn.finance)
- [Seafood](https://github.com/yearn/dashboard_ui)
- [ySync](https://sync.yearn.farm/)
- [yData](https://ydata.vercel.app/)
- [Yearn Watch](https://yearn.watch)
- [Yearn SDK](https://github.com/yearn/yearn-sdk)
- Some other projects

yDaemon provide us with a full scale API, ready to compute various elements, from the vault list, to the harvest, from the prices to the meta elements and much more.
A full documentation is available here: https://ydaemon.yearn.farm

While relying mostly on the subgraph with the V1, we are now trying to bring a new version which would use mostly (target 90%) a direct connection with a set of node to compute the relevant data. The idea is to be able to bootstrap yDaemon in a few minutes, grab all the stuff we need to at least mimic what we have from the subgraph, while bringing more customisation, more routes, more.

Scope includes:
- yDaemon API
- yDaemon documentation
- Risk framework
- Vaults/Tokens/Protocols/Strategies metadata

### Plan

The API will evolve with our needs, but here are some stuff we plan to work on

- [ ] Merge the experimental branch to be the default one
- [ ] Write an historical APY route based on all available events
- [ ] Write a route to get, for a specific vaults, all the earnings for all strategies with the fee breakdown
- [ ] Write "scoped-app", which could be started via env variable or argument, to be able to start only some process (ex: yBribe system only).
- [ ] Build a load balancer system and some try-catch for multiple node architecture
- [ ] Bring more indexers to catch new events as they are emited by the nodes and process them.
- [ ] Fix the various issues, warnings and errors (prices, missing meta files, missing risk framework).
- [ ] Build new routes for our needs, and new daemons to get the required data.
- [ ] Write more tests
- [ ] Much more

### Deadline

2023-02-27

### People

- Major (no grant)
- Dark (no grant)

Possible contributors:
- Borrito
- Murderteeth

### Money

We would like to request a 9000 DAI grant for a 3 month initial period which will be used to pay contributors.
We plan to distribute a grant for each person in charge of a project and use bounties to fund other contributions linked to projects in maintenance mode or isolated contributions.

### Amount

9000

### Wallet address

0x0

### Reporting

Monthly

**Comment by kyhoon** [comment]
## Monthly Report for yDaemon - December

[The experimental branch has been merged to the main branch](https://github.com/yearn/ydaemon/pull/84), and furthermore, [the indexers for vaults and strategies have been implemented](https://github.com/yearn/ydaemon/pull/147). As mentioned in the above request, we plan to provide the historical APY and the breakdown of earnings for a given vault/strategy from the indexed events. To this end, we started with adding [a simple pricing system using external APIs](https://github.com/yearn/ydaemon/pull/172).

Many other PRs were done this month for maintaining the data integrity of yDaemon, namely the risk framework and the metadata of strategies and vaults. We share some examples for these maintanence efforts in the following.

### Risk Framework

- https://github.com/yearn/ydaemon/pull/153
- https://github.com/yearn/ydaemon/pull/164
- https://github.com/yearn/ydaemon/pull/167
- https://github.com/yearn/ydaemon/pull/171

We discovered that there are a number of discrepancies in our perception of the risk scores and the actual rubric (e.g. high scores for Curve and Balancer pools), which kept us from adding the risk scores to the new frontend.
They will be handled together with the missing scores (e.g. StrategyCurveyCRV) this month.

### Metadata

- https://github.com/yearn/ydaemon/pull/162
- https://github.com/yearn/ydaemon/pull/168
- https://github.com/yearn/ydaemon/pull/174
- https://github.com/yearn/ydaemon/pull/175
