### ISSUE TITLE
yTreasury BR 1

### ISSUE THREAD

**Issue by wavey0x** [yearn/ychad-audit#210]
### Scope

- New 3/5 multisig to replace yTrades: `0xca540000ac07e1c0Ce80935880baA51512CD10F7`
- Handles token conversion transactions from treasury
- Manages treasury holdings with directive from yBudget
- Transactions
    - Executes timely trades
    - Pays contributor grants
    - Tops up developer wallets with ETH
- Sets farming guidelines
    - what can / cannot be farmed with treasury assets
    - bridging guidelines
    - risk guidelines

### Plan

- Assist yBudget in defining target treasury asset allocations
- Execute timely trades
- Develop processes to reduce complexity of holdings and streamline token transfers
    - Establish separate POL holdings

### Deadline

2024-07-30

### People

- wavey
- micky 
- lance
- corn
- tapir

### Money

$4,000 / month / person
$60,000 total for 3 month period

### Amount (Total)

60000

### Wallet address

0xca540000ac07e1c0Ce80935880baA51512CD10F7

### Reporting

Once

**Comment by 0xPickles** [comment]
Closing withdrawn by the proposers
